id: I7D388604
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T14:19:25+00:00'
last_modified: '2022-06-08T01:46:06.783775+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC415
  title: སྤྱི་དོན་ཤེས་བྱ་རབ་གསལ། གསུང་སྒྲོས་ཕན་བྱེད་རིག་པའི་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FF3A:
      image_group_id: I2PD18358
      title: ''
      total_pages: 326
      order: 1
      base_file: FF3A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
