id: P004535
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:30:39.559860
source_metadata:
  id: bdr:W1AC415
  title: སྤྱི་དོན་ཤེས་བྱ་རབ་གསལ། གསུང་སྒྲོས་ཕན་བྱེད་རིག་པའི་མཛོད།
  author: ''
  volumes:
    03ed2c0de4be4658bc78fd1eb84786c6:
      image_group_id: I2PD18358
      title: ''
      volume_number: 1
      total_pages: 326
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
